### ISSUE TITLE
something wrong with "common/AssetBundleManager.cs"

### ISSUE THREAD

**Issue by kkhtg** [blackwitch/EasyPatcher#1]
Original code

// Make sure all dependencies are loaded
foreach(var dependency in dependencies)
{
    if (m_DownloadingErrors.TryGetValue(assetBundleName, out error) )
    {
        return bundle;
    }
    // Wait all the dependent assetBundles being loaded.
    LoadedAssetBundle dependentBundle;
    m_LoadedAssetBundles.TryGetValue(dependency, out dependentBundle);
    if (dependentBundle == null){
        return null;
    }
}

Modified

// Make sure all dependencies are loaded
foreach(var dependency in dependencies){
    if (_downloadingErrors.TryGetValue(dependency, out error) ){
        return null;
    }
    // Wait all the dependent assetBundles being loaded.
    LoadedAssetBundle dependentBundle;
    _loadedAssetBundles.TryGetValue(dependency, out dependentBundle);
    if (dependentBundle == null){
        return null;
    }
}

**Comment by blackwitch** [comment]
Hi there ~ Thanks a lot.

I agree the problem but the code is from unity5 sample project.

((
    You can see the article here (http://forum.unity3d.com/threads/new-assetbundle-build-system-in-unity-5-0.293975/)
    And you can download the sample project here(http://files.unity3d.com/vincent/assetbundle-demo/users_assetbundle-demo.zip)
))

I made a thread about this issue on the offical Community/forum on Unity5 site.
(  http://forum.unity3d.com/threads/a-small-problem-in-assetbundlemanager-cs.325000/  )

So, I'll fix this problem after I got the reply.

Have a good day ~ 

Kind regards,
blackwitch

**Comment by blackwitch** [comment]
I got the reply from Unity5 forum. 

the reply is as below.

---

Hi

Yes, you're right. The purpose is to check if the dependencies have been loaded correctly. If we meet one dependency are failed to download, we simply return the bundle itself(You can change the behavior here according to your case).

## Thanks for reporting.

Thanks kkhtg. 

Have a nice day. ~ :)
